import { Request, Response } from "express";
import jwt from "jsonwebtoken";

import Locals from "../../providers/Locals";
import Log from "../../middlewares/Log";
import {
  errorResponse,
  failResponse,
  successResponse,
} from "../../helpers/JSend";

import fs from "fs";
import { userDB, mainDB, connections } from "../../providers/Database";
import { getSettingInt } from "../../helpers/settings";

interface MasterRow {
  id: number;
  date: Date | string;
  doctorId: number;
  tomogramTypeId: number;
}

interface DetailRow {
  id: number;
  masterid: number;
  tomogrampartid: number;
  narration: string | null;
}

export const listTomogramsController = async (req: Request, res: Response) => {
  const opid = Number(req.query.opid);
  if (!opid) return res.status(400).json(failResponse("Invalid opid"));
  try {
    const op = await mainDB.OpRegisters.findOne({ where: { opid } });
    if (!op) return res.status(404).json(failResponse("Invalid OP Number"));

    const masters = (await mainDB.TomogramMasters.findAll({
      where: { opid: (op as unknown as { id: number }).id },
      order: [['date', 'DESC'], ['id', 'DESC']],
    })) as unknown as MasterRow[];

    const masterIds = masters.map((m) => m.id);
    const details = (masterIds.length === 0
      ? []
      : await mainDB.TomogramDetails.findAll({
          where: { masterid: masterIds },
          order: [['id', 'ASC']],
        })) as unknown as DetailRow[];

    const byMaster = new Map<number, { id: number; tomogramPartId: number; narration: string }[]>();
    for (const d of details) {
      const list = byMaster.get(d.masterid) ?? [];
      list.push({ id: d.id, tomogramPartId: d.tomogrampartid, narration: d.narration ?? '' });
      byMaster.set(d.masterid, list);
    }

    const data = masters.map((m) => ({
      id: m.id,
      dateTime: new Date(m.date).toISOString(),
      doctorId: m.doctorId,
      tomogramTypeId: m.tomogramTypeId,
      details: byMaster.get(m.id) ?? [],
    }));

    return res.status(200).json(successResponse(data));
  } catch (e: any) {
    Log.error(e.message);
    return res.status(500).json(errorResponse("Internal Server Error", e.message));
  }
};

export const uploadTomogramController = async (req: Request, res: Response) => {
  const { opid, narrations } = req.body;
  let descriptions = narrations;
  const files = req.files as Express.Multer.File[];
  
  Log.info("Tomogram Payload :: Request Received");

  /*
   * below code will read the data from the upload folder. 
   * Multer will automatically upload the file in that folder with an autogenerated name
   */
  // let descriptions: [];
  try {
    if (!Array.isArray(descriptions)) {
      Log.error("Tomogram Payload :: Invalid param 'description'");
      return res
        .status(400)
        .send(failResponse("Expecting narrations as an Array!"));
    }
  } catch (err) {
    descriptions = [];
  }

  const [doctorId, tomogramTypeId, tomogramPartId] = await Promise.all([
    getSettingInt('PrimaryDoctorID', 1),
    getSettingInt('TomogramTypeID', 6),
    getSettingInt('TomogramPartID', 2),
  ]);

  connections
    .get("main")
    ?.transaction()
    .then(async (t) => {
      const op = await mainDB.OpRegisters.findOne({ where: { opid } });
      if (!op) return res.send(failResponse("Invalid OP Number"));
      mainDB.TomogramMasters.create(
        { opid: op?.id, doctorId, tomogramTypeId, narration: "" },
        { transaction: t }
      )
        .then((result) => {
          Log.info("Tomogram Detail Creation :: Started");
          let promises = [];
          for (let i = 0; i < files.length; i++) {
            let narration = descriptions[i] ? descriptions[i] : "";
            let newPromise = mainDB.TomogramDetails.create(
              { masterid: result.id, tomogrampartid: tomogramPartId, narration },
              { transaction: t }
            );
            promises.push(newPromise);
          }
          return Promise.all(promises);
        })
        .then((data) => {
          Log.info("Tomogram File Rename :: Started");
          files.forEach((file, index) => {
            Log.info(`Tomogram File OldRename :: ${file.filename}`);
            let savedData = data[index];
            // let newFileName = `TOMOGRAM${savedData.masterid}_${savedData.id}.jpg`;
            let newFileName = `${savedData.masterid}_${savedData.id}.JPEG`;
            fs.renameSync(file.path, file.destination + newFileName);
            Log.info(`Tomogram File NewRename :: ${newFileName}`);
          });
          Log.info("Tomogram File Rename :: Completed");
          t.commit();
          res.status(200).send(successResponse(data));
        })
        .catch((err) => {
          Log.info(`Tomogram Error:: ${err.message}}`);
          t.rollback();
          console.log(err.message);
          res.status(500).send(errorResponse(err.message));
        });
    });
};
